<a href="https://colab.research.google.com/github/satyam0402/python-ml/blob/main/Chapter2_Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NumPy
1. Allows several mathematical operations
2. Faster Operations

In [2]:
# Importing NumPy
import numpy as np

Example 1: List vs NumPy - TIME TAKEN COMPARISON

In [2]:
#Using process_time function from time library
from time import process_time

Time Taken by List

In [13]:
#Creating a list using a for loop with 10000 items
my_list = (i for i in range(1000000))
# initializing start time with process time
start_time = process_time()
# Adding some values to each item from the list
my_list = (i+5 for i in my_list)
end_time = process_time() # Call the process_time() function to get the current time
time_taken = end_time - start_time
print("Time taken by list = ", time_taken)

Time taken by list =  0.00012888600000060535


Time Taken by NumPy Array

In [14]:
my_array = np.array([i for i in range(1000000)])
start_time = process_time()
my_array = (i+5 for i in my_array)
end_time = process_time()
time_taken = end_time - start_time
print("Time taken by array = ", time_taken)

Time taken by array =  0.00012377200000024402


Difference between List and np.array

In [15]:
#List
my_list = [1,2,3,4,5]
print(my_list)
type(my_list)

#Array
my_array = np.array([1,2,3,4,5])
print(my_array)
type(my_array)

# List elements are separated by "," whereas array elements are not.

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

Different Dimensions of arrays

In [18]:
# 1D
my_array = np.array([1,2,3,4,5])
print(my_array)
print(my_array.shape) #(rows,column)

#2D
my_array = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(my_array)
print(my_array.shape) #(rows,column)

#Float in arrays
my_array = np.array([(1.1,2,3.5,4,5),(6,7.3,8,9,10)],dtype=float)
print(my_array)
print(my_array.shape) #(rows,column)

[1 2 3 4 5]
(5,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 1.1  2.   3.5  4.   5. ]
 [ 6.   7.3  8.   9.  10. ]]
(2, 5)


Initial Placeholder for numpy array where each element in the array is initialized to zero

In [3]:
#Zeros
my_initial_array_Zeros = np.zeros((5,5)) #np.zeros function is used to create array with all zeros
print(my_initial_array_Zeros)
#Ones
my_initial_array_Ones = np.ones((5,5)) #np.ones function is used to create array with all ones
print(my_initial_array_Ones)

#Arrays of particular value
my_valued_array = np.full((5,5),5) #np.full function is used to create array with all particular value
print(my_valued_array)

# Identity matrix
my_identity_matrix = np.eye(5) #np.eye function is used to create identity matrix
print(my_identity_matrix)

#Array with random values
my_random_array = np.random.random((5,5)) #np.random.random function is used to create array with random values
print(my_random_array)

#Array with random values within specific range
my_random_array = np.random.randint(10,100,(5,5)) #np.random.randint function is used to create array with random values within specific range
print(my_random_array)

#Array with evenly space  ---> Number of values required
my_evenly_spaced_array = np.linspace(10,20,6) #np.linespace function is used to create array with evenly space values
print(my_evenly_spaced_array)

#Array with evenly space steps ---> Steps
my_step_array = np.arange(10,100,5) #np.arange function is used to create array with evenly space steps
print(my_step_array)

#List to Numpy Array
my_list = [1,2,3,1,2,3]
my_array = np.array(my_list)
print(my_array)





[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.54330943 0.26748486 0.06994801 0.67916094 0.81872137]
 [0.91038816 0.00954161 0.73596436 0.00896791 0.35104823]
 [0.00101353 0.54273094 0.84994797 0.95986588 0.71332291]
 [0.39883164 0.81642853 0.16259424 0.70808341 0.00153545]
 [0.91180211 0.04261923 0.71517962 0.97885533 0.48626861]]
[[31 70 91 66 34]
 [95 21 49 60 27]
 [90 78 26 33 91]
 [45 49 66 41 23]
 [95 37 39 20 99]]
[10. 12. 14. 16. 18. 20.]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[1 2 3 1 2 3]


NumPy Array Analysis

In [4]:
#Numpy array
new_array = np.random.randint(10,90,(3,5))
print(new_array)

[[42 27 24 73 65]
 [43 13 42 89 67]
 [71 51 66 14 82]]


In [9]:
#Get Array Dimension
print(new_array.shape)
#Get Number of Dimension
print(new_array.ndim)
#Get array size
print(new_array.size)
#Get data type
print(new_array.dtype)

(3, 5)
2
15
int64


Math Operation on Arrays

In [10]:
list1 = [ 1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 +list2) #Concatenation or joining list1 and list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [14]:
my_array1 = np.random.randint(0,20,(5,5))
my_array2 = np.random.randint(20,40,(5,5))
print(my_array1)
print(my_array2)
print(my_array1 + my_array2)
print(my_array1 - my_array2)
print(my_array1 * my_array2)
print(my_array1 / my_array2)

#Using np.operator
print(np.add(my_array1,my_array2))
print(np.subtract(my_array1,my_array2))
print(np.multiply(my_array1,my_array2))

[[19 16 10  6  5]
 [11  2 13 18  4]
 [ 9 10 18  2 12]
 [ 2  7  6 11 10]
 [17 13 11  6 18]]
[[38 35 37 24 24]
 [27 32 34 36 29]
 [28 30 25 33 29]
 [34 35 26 36 28]
 [26 26 33 37 26]]
[[57 51 47 30 29]
 [38 34 47 54 33]
 [37 40 43 35 41]
 [36 42 32 47 38]
 [43 39 44 43 44]]
[[-19 -19 -27 -18 -19]
 [-16 -30 -21 -18 -25]
 [-19 -20  -7 -31 -17]
 [-32 -28 -20 -25 -18]
 [ -9 -13 -22 -31  -8]]
[[722 560 370 144 120]
 [297  64 442 648 116]
 [252 300 450  66 348]
 [ 68 245 156 396 280]
 [442 338 363 222 468]]
[[0.5        0.45714286 0.27027027 0.25       0.20833333]
 [0.40740741 0.0625     0.38235294 0.5        0.13793103]
 [0.32142857 0.33333333 0.72       0.06060606 0.4137931 ]
 [0.05882353 0.2        0.23076923 0.30555556 0.35714286]
 [0.65384615 0.5        0.33333333 0.16216216 0.69230769]]
[[57 51 47 30 29]
 [38 34 47 54 33]
 [37 40 43 35 41]
 [36 42 32 47 38]
 [43 39 44 43 44]]
[[-19 -19 -27 -18 -19]
 [-16 -30 -21 -18 -25]
 [-19 -20  -7 -31 -17]
 [-32 -28 -20 -25 -18]
 [ -9 -13 -22 -31  -8

Transpose of an Array

In [19]:
my_array = np.random.randint(0,10,(3,2))
print(my_array)
print(my_array.shape)
my_tansposed_array = np.transpose(my_array)
print(my_tansposed_array)
print(my_tansposed_array.shape)

[[9 0]
 [5 4]
 [9 2]]
(3, 2)
[[9 5 9]
 [0 4 2]]
(2, 3)


Reshaping Array

In [23]:
my_array = np.random.randint(0, 10, (3,2))
print(my_array)
print(my_array.shape)
#Reshaping my_array
my_reshaped_array = my_array.reshape((2,3))
print(my_reshaped_array)

[[9 1]
 [9 2]
 [6 1]]
(3, 2)
[[9 1 9]
 [2 6 1]]
