<a href="https://colab.research.google.com/github/satyam0402/python-ml/blob/main/Chapter2_Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NumPy
1. Allows several mathematical operations
2. Faster Operations

In [2]:
# Importing NumPy
import numpy as np

Example 1: List vs NumPy - TIME TAKEN COMPARISON

In [2]:
#Using process_time function from time library
from time import process_time

Time Taken by List

In [13]:
#Creating a list using a for loop with 10000 items
my_list = (i for i in range(1000000))
# initializing start time with process time
start_time = process_time()
# Adding some values to each item from the list
my_list = (i+5 for i in my_list)
end_time = process_time() # Call the process_time() function to get the current time
time_taken = end_time - start_time
print("Time taken by list = ", time_taken)

Time taken by list =  0.00012888600000060535


Time Taken by NumPy Array

In [14]:
my_array = np.array([i for i in range(1000000)])
start_time = process_time()
my_array = (i+5 for i in my_array)
end_time = process_time()
time_taken = end_time - start_time
print("Time taken by array = ", time_taken)

Time taken by array =  0.00012377200000024402


Difference between List and np.array

In [15]:
#List
my_list = [1,2,3,4,5]
print(my_list)
type(my_list)

#Array
my_array = np.array([1,2,3,4,5])
print(my_array)
type(my_array)

# List elements are separated by "," whereas array elements are not.

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

Different Dimensions of arrays

In [18]:
# 1D
my_array = np.array([1,2,3,4,5])
print(my_array)
print(my_array.shape) #(rows,column)

#2D
my_array = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(my_array)
print(my_array.shape) #(rows,column)

#Float in arrays
my_array = np.array([(1.1,2,3.5,4,5),(6,7.3,8,9,10)],dtype=float)
print(my_array)
print(my_array.shape) #(rows,column)

[1 2 3 4 5]
(5,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 1.1  2.   3.5  4.   5. ]
 [ 6.   7.3  8.   9.  10. ]]
(2, 5)


Initial Placeholder for numpy array where each element in the array is initialized to zero

In [15]:
#Zeros
my_initial_array_Zeros = np.zeros((5,5)) #np.zeros function is used to create array with all zeros
print(my_initial_array_Zeros)
#Ones
my_initial_array_Ones = np.ones((5,5)) #np.ones function is used to create array with all ones
print(my_initial_array_Ones)

#Arrays of particular value
my_valued_array = np.full((5,5),5) #np.full function is used to create array with all particular value
print(my_valued_array)

# Identity matrix
my_identity_matrix = np.eye(5) #np.eye function is used to create identity matrix
print(my_identity_matrix)

#Array with random values
my_random_array = np.random.random((5,5)) #np.random.random function is used to create array with random values
print(my_random_array)

#Array with random values within specific range
my_random_array = np.random.randint(10,100,(5,5)) #np.random.randint function is used to create array with random values within specific range
print(my_random_array)

#Array with evenly space  ---> Number of values required
my_evenly_spaced_array = np.linspace(10,20,6) #np.linespace function is used to create array with evenly space values
print(my_evenly_spaced_array)

#Array with evenly space steps ---> Steps
my_step_array = np.arange(10,100,5) #np.arange function is used to create array with evenly space steps
print(my_step_array)




[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.57107076 0.40204775 0.43447169 0.6179334  0.14628363]
 [0.12820776 0.94185041 0.77623773 0.01513873 0.78907949]
 [0.32687901 0.28072876 0.31434226 0.65040994 0.91017884]
 [0.53958881 0.33150477 0.12452479 0.4396856  0.55038673]
 [0.57936526 0.76434798 0.33513268 0.01409127 0.70769588]]
[[90 34 58 56 34]
 [46 56 82 61 81]
 [58 91 49 81 63]
 [52 35 72 73 69]
 [40 49 30 73 46]]
[10. 12. 14. 16. 18. 20.]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
